### ISSUE TITLE
Scope issues

### ISSUE THREAD

**Issue by TimLoveCambridge** [CambridgeEngineering/PartIA-Computing-Michaelmas#17]
Issues regarding scope are made more confusing by the notebooks. Sometimes the code in a cell only worked because of a variable that had by chance been set in an earlier cell. I don't know what to do about that; insist that each solution works in a self-contained cell?

**Comment by garth-wells** [comment]
Splitting a complex problem across cells should be encouraged, e.g. splitting the computation from the plotting.

Scoping is inherent to the language and user errors will happen. Mistakes are part of learning.
