### ISSUE TITLE
Some features that could be removed

### ISSUE THREAD

**Issue by TimLoveCambridge** [CambridgeEngineering/PartIA-Computing-Michaelmas#18]
* Decorators

* %time - a mysterious feature for which there's a more general and easily understood alternative (even if the results might not be as good)

import time
start_time = time.time()
print("hello")
end_time = time.time()
print("Time taken=",end_time - start_time)

* list comprehensions - because they're not easily transferable to other languages, and they're guessed/borrowed without being understood

**Comment by garth-wells** [comment]
List comprehension can be explicitly marked as optional and not required for the non-optional questions. It should be retained (but marked as optional) for completeness and it can provide advanced optional exercises for experienced programmers.

**Comment by garth-wells** [comment]
Can't find any decorators - just some Jupyter magic functions
