### ISSUE TITLE
Small Typo in Notebook 3

### ISSUE THREAD

**Issue by NikhilAntonyU** [CambridgeEngineering/PartIA-Computing-Michaelmas#29]
Hate to be pedantic but I believe there is a small typo in the third code box in the section 'Strings' in Notebook 3. 
Here is what is written
```
# Get first six characters, print and check type
s3 = my_string[0:6]
print(s3)
print(type(s2))

# Get last four characters and print
s3 = my_string[-4:]
print(s3)
```
The line `print(type(s2))`  (line 4) I think it should be `print(type(s3))` . Whilst both yield the same output the new line actually checks the type of s3.

**Comment by garth-wells** [comment]
Thanks - fixed.
