### ISSUE TITLE
Maths equation in `02 Exercises.ipynb` written wrong

### ISSUE THREAD

**Issue by strongdingstar** [CambridgeEngineering/PartIA-Computing-Michaelmas#35]
In line 75 of `02 Exercises.ipynb`, the expression of $f(x)$ is written as $f(x) = -\frac{x^{5}}{10} + x^3 - 10x^2 + 4x + 7$. However, all following code assume $f(x)$ as $f(x) = \frac{x^{5}}{10} + x^3 - 10x^2 + 4x + 7$, with out the minus sign at the front
CRSid: zd316

**Comment by flamancini** [comment]
fixed, thanks
