### ISSUE TITLE
End of Notebook 4

### ISSUE THREAD

**Issue by TimLoveCambridge** [CambridgeEngineering/PartIA-Computing-Michaelmas#5]
At the End of Notebook 4 there's an "Optional extension" heading but nothing after

**Comment by garth-wells** [comment]
At the very end I see:

**Optional extension**

Use recursion to write a `compute_root` function that does not require a `for` or `while` loop.

**Comment by TimLoveCambridge** [comment]
That's what I see too, now (new session).

**Comment by TimLoveCambridge** [comment]
It's happened again. The banner at the bottom of the page sometimes covers the bottom line of text completely. Sometimes it covers half the line. Sometimes I can see all of the bottom line. Scrolling and resizing the window doesn't help. I suggest pro tem that you add some empty lines at the end of the page.

Mozilla Firefox 45.4.0 on Centos 7.2

**Comment by garth-wells** [comment]
See https://github.com/Microsoft/AzureNotebooks/issues/15.
