### ISSUE TITLE
Notebook 9 - comments and typos

### ISSUE THREAD

**Issue by TimLoveCambridge** [CambridgeEngineering/PartIA-Computing-Michaelmas#6]
"There are two types of program errors: syntax errors and exceptions" - using the word "exceptions" here (rather than "run-time errors") leads to awkward discussions when talking about error-handing and languages more generally - e.g. "If the language you're using doesn't support exceptions you'll have to deal with exceptions by returning special values.

"guard against easy-to-detect to errors" -> "guard against easy-to-detect errors"

"This help detect errors that might inadvertently creep in to a program" -> "This helps detect errors that might inadvertently creep into a program"

"Try changing one of the check" -> "Try changing one of the checks"

**Comment by garth-wells** [comment]
I've fixed the typos.

Exceptions and runtime errors are not the same (e.g. http://net-informations.com/faq/general/error.htm). We have the good fortune to be working with just one language at this stage, so we don't have to contrast and compare.
